[package]
name = "rsearth"
version = "0.1.0"
authors = ["shioleap <shioleap@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7"

[dependencies.amethyst]
version="0.13"
features=["vulkan", "no-slow-safety-checks"]

