[package]
name = "rsearth"
version = "0.1.0"
authors = ["shioleap <shioleap@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7"
rayon = "1.3"
#winit = "0.28"

[dependencies.amethyst]
version="0.15"
features=["vulkan", "no-slow-safety-checks"]

